backend:
  name: git-gateway
  repo: shubhampriyesh24-oss/jbic
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "school"
    label: "School Content"
    folder: "content/school"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
