backend:
  name: git-gateway
  branch: main # ya master, jo aapke github repo mein hai

media_folder: "public/images"
public_folder: "images"

collections:
  - name: "school"
    label: "School Content"
    folder: "content/school"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
